name: Sync Upstream Full (Code & Releases)

on:
  schedule:
    - cron: '0 0 */16 * *'
  workflow_dispatch:

jobs:
  sync-code:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream Code
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/jbeder/yaml-cpp.git"
          source_branch: "master"       
          destination_branch: "master"  
          github_token: ${{ secrets.SYNC_TOKEN }}

  sync-releases:
    runs-on: ubuntu-latest
    needs: sync-code 
    steps:
      - name: Clone Upstream Releases
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.SYNC_TOKEN }}
          src_repo: jbeder/yaml-cpp
